-- 1. Display First 10 Records
select * from Customer limit 10;

-- 2. Total Revenue Generated by Male vs Female Customers
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;


-- 3. Customers Who Used a Discount but Spent More Than the Average Purchase Amount
SELECT
    customer_id,
    gender,
    category,
    purchase_amount,
    discount_applied
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >
(
    SELECT AVG(purchase_amount)
    FROM customer
);

-- 4. Top 5 Products with Highest Average Review Rating

SELECT
    item_purchased,
    ROUND(AVG(review_rating)::numeric,2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;


-- 5. Compare Average Purchase Amount Between Shipping Types

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount)::numeric,2) AS average_purchase
FROM customer
GROUP BY shipping_type
ORDER BY average_purchase DESC;

-- 6. Revenue Generated by Each Category
SELECT
    category,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;

-- 7. Number of Customers in Each Age Group

SELECT
    age_group,
    COUNT(*) AS total_customers
FROM customer
GROUP BY age_group
ORDER BY total_customers DESC;

-- 8. Top 10 Highest Spending Customers

SELECT
    customer_id,
    purchase_amount
FROM customer
ORDER BY purchase_amount DESC
LIMIT 10;

-- 9. Customer Segmentation Using CASE Statement

SELECT
    customer_id,
    purchase_amount,

    CASE
        WHEN purchase_amount >= 80 THEN 'High Value'
        WHEN purchase_amount >= 50 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment

FROM customer;

s

-- 10.Subscription vs Non-Subscription Revenue
SELECT
    subscription_status,
    COUNT(*) AS customers,
    SUM(purchase_amount) AS revenue,
    ROUND(AVG(purchase_amount)::numeric,2) AS average_purchase
FROM customer
GROUP BY subscription_status;


